#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/MurisKamaa permanent;/" /etc/nginx/sites-available/default
service nginx start
